name: email_water_department
on:
  #schedule:
  #  - cron: '0 * * * *'
  push:
    branches:
      - main

jobs: 
    send_email:
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
             with:
                 python-version: '3.9'
          - run: pip install -r requirements.txt
          - run: main.py

env:
            GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
            GOOGLE_APP_PWD: ${{ secrets.GOOGLE_APP_PWD }}
            HOME_ADDRESS: ${{ secrets.HOME_ADDRESS }}
