name: email_water_department
on:
  #schedule:
  #  - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for demo Python project  
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   run: |
     python main.py

env:
            GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
            GOOGLE_APP_PWD: ${{ secrets.GOOGLE_APP_PWD }}
            HOME_ADDRESS: ${{ secrets.HOME_ADDRESS }}
