name: email_water_department
on:
  #schedule:
  #  - cron: '0 * * * *'
  push:
    branches:
      - main
jobs: 
  send_email:
    runs-on: ubuntu-latest
    name: send email to water department
      steps:
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'  
        - name: Install Dependencies
          run: pip install -r requirements.txt
        - name: Run python script
          run: python main.py

env:
            GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
            GOOGLE_APP_PWD: ${{ secrets.GOOGLE_APP_PWD }}
            HOME_ADDRESS: ${{ secrets.HOME_ADDRESS }}
